config/routes.rb
Rails.application.routes.draw do
  resources :users, only: :index
  resources :charts, only: :index

  resources :posts, only: [:index, :show, :edit, :update] do
    collection do
      post :bulk_publish
      post :bulk_unpublish
    end
  end

  resources :things do
    post :approve, on: :member
    post :reject, on: :member
  end

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  # Attributes
  # title           :string
  # description     :text
  #
  # draft           :boolean
  # published_at    :datetime
  #
  # score           :integer
  #
  # timestamps

  scope :published, -> { where(draft: false) }
  scope :unpublished, -> { where(draft: true) }

  def to_s
    title
  end

  def publish!
    update!(draft: false, published_at: Time.zone.now)
  end

  def unpublish!
    update!(draft: true, published_at: nil)
  end

end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :user

  effective_resource do
    title           :string
    description     :text

    approved        :boolean

    timestamps
  end

  scope :deep, -> { includes(:user) }
  scope :sorted, -> { order(:title) }

  def to_s
    title
  end

  def approve!
    update!(approved: true)
  end

  def reject!
    update!(approved: false)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  # Attributes
  # first_name    :string
  # last_name     :string
  # city          :string
  #
  # timestamps

  scope :sorted, -> { order(:first_name) }

  def to_s
    [first_name, last_name].compact.join(' ')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  def index
    @datatable = ChartsDatatable.new
    @page_title = 'Chart Example'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Effective::CrudController

  def index
    @datatable = PostsDatatable.new
    @page_title = 'Advanced Example (Posts)'
  end

  def show
    @post = Post.find(params[:id])
    @page_title = "Post #{@post.id}"
  end

  def edit
    @post = Post.find(params[:id])
    @page_title = "Edit Post #{@post.id}"
  end

  def bulk_publish
    @posts = Post.where(id: params[:ids])

    begin
      @posts.each { |post| post.publish! }
      render json: { status: 200, message: "Successfully published #{@posts.length} posts." }
    rescue => e
      render json: { status: 500, message: 'An error occured while publishing a post.' }
    end
  end

  def bulk_unpublish
    @posts = Post.where(id: params[:ids])

    begin
      @posts.each { |post| post.unpublish! }
      render json: { status: 200, message: "Successfully unpublished #{@posts.length} posts." }
    rescue => e
      render json: { status: 500, message: 'An error occured while unpublishing a post.' }
    end
  end

  def permitted_params
    params.require(:post).permit!
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  include Effective::CrudController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @datatable = UsersDatatable.new
    @page_title = 'Simple Example (Users)'
  end
  
end

app/views/charts/index.html.erb
<h1><%= @page_title %></h1>

See the code:
<%= link_to 'app/datatables/charts_datatable.rb', 'https://github.com/code-and-effect/effective_datatables_demo/blob/master/app/datatables/charts_datatable.rb', target: '_blank' %>

<%= render_datatable_charts(@datatable) %>

app/views/layouts/_footer.html.erb
<hr>
<div class='text-center my-4'>
  <small class='text-muted'>
    Copyright &copy; <%= Time.zone.now.year %>
    <a href='https://codeandeffect.com'>Code and Effect</a>
  </small>
</div>

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
  <a class="navbar-brand" href="/">gem 'effective_datatables'</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div id='navbarSupportedContent' class='collapse navbar-collapse'>
    <ul class='navbar-nav mr-auto'>
      <li class='nav-item <%= 'active' if request.path.start_with?(users_path) || request.path == '/' %>'>
        <%= link_to 'Simple', users_path, class: 'nav-link' %>
      </li>
      <li class='nav-item <%= 'active' if request.path.start_with?(posts_path) %>'>
        <%= link_to 'Advanced', posts_path, class: 'nav-link' %>
      </li>
      <li class='nav-item <%= 'active' if request.path.start_with?(charts_path) %>'>
        <%= link_to 'Charts', charts_path, class: 'nav-link' %>
      </li>
      <li class='nav-item <%= 'active' if request.path.start_with?(things_path) %>'>
        <%= link_to 'Inline CRUD', things_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'Github', 'https://github.com/code-and-effect/effective_datatables_demo', class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>gem 'effective_datatables'</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class='container my-4'>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.haml
= effective_form_with(model: post) do |f|
  = f.text_field :title
  = f.text_area :description
  = f.check_box :draft
  = f.date_field :published_at
  = f.number_field :score
  = f.save

app/views/posts/_post.html.haml
.card.mb-4
  .card-body
    %h5.card-title= post.title
    %p 
      %span.badge.badge-info SCORE: #{post.score}

    %p= post.description

app/views/posts/index.html.erb
<h1><%= @page_title %></h1>

See the code: 
<%= link_to 'app/datatables/posts_datatable.rb', 'https://github.com/code-and-effect/effective_datatables_demo/blob/master/app/datatables/posts_datatable.rb', target: '_blank' %>
<br><br>

<%= render_datatable(@datatable) %>

app/views/things/_form.html.haml
= effective_form_with(model: thing) do |f|
  = f.select :user_id, User.sorted.all
  = f.text_field :title
  = f.text_area :description
  = f.check_box :approved

  = f.save

app/views/things/_thing.html.haml
%table.table
  %tbody
    %tr
      %th User
      %td= thing.user
    %tr
      %th Title
      %td= thing.title
    %tr
      %th Description
      %td= thing.description
    %tr
      %th Approved
      %td= thing.approved

app/views/things/index.html.erb
<h1><%= @page_title %></h1>

See the code:
<%= link_to 'app/datatables/things_datatable.rb', 'https://github.com/code-and-effect/effective_datatables_demo/blob/master/app/datatables/things_datatable.rb', target: '_blank' %>

<%= render_datatable(@datatable, inline: true) %>

app/views/users/index.html.erb
<h1><%= @page_title %></h1>

See the code: 
<%= link_to 'app/datatables/users_datatable.rb', 'https://github.com/code-and-effect/effective_datatables_demo/blob/master/app/datatables/users_datatable.rb', target: '_blank' %>

<%= render_datatable(@datatable) %>